### PR TITLE
add more stats

### PR DESCRIPTION
**Pull request by Furtif**
fix https://github.com/Map-A-Droid/MAD/pull/87#issuecomment-464856928

### CODE REVIEW

**Comment by sn0opy** [comment]
Well, it's still not clear, what this actually fixes or what it actually does 🤔

**Comment by Furtif** [comment]
add more stats form file and create player data for get player name etc.. but part playerdata is no implemented to apk mad Grennith say add this to next

**Comment by cecpk** [comment]
we have to wait for the needed data from pogodroid

**Comment by Furtif** [comment]
@sn0opy  @cecpk  maybe close this

**Pull request closed without merging**
