### PR TITLE
Handle protocol type 156 to update gym details

### PR DESCRIPTION
**Pull request by rfuchs**
This makes it possible to open a gym and automatically populate the
details (name, url, and description) of the gym in the DB.

### CODE REVIEW

**Comment by cecpk** [comment]
Round 1 - fight

**Comment by muckelba** [comment]
Considering [this](https://mad-docs.readthedocs.io/en/latest/common-issues/faq/#is-it-planned-to-see-gym-defenders-trainers-in-gyms) statement, i think name, url and description should be fine. But your PR doesn't has any automatic mechanic to click on the gyms, so the benefits right now is not *that* huge. Still a good QoL update :)

**Comment by rfuchs** [comment]
For a new installation, it was easier for me to do it this way than to manually fill in the details :)

Automatic clicking on gyms can be added as a second step.

**Comment by muckelba** [comment]
Btw, we have an import script for that :D

**Pull request merged**
