### PR TITLE
Routecalc in MADmin

### PR DESCRIPTION
**Pull request by Expl0dingBanana**
Implementation for #618 .  Routecalcs are now editable in MADmin.  They are accessible on the area page on the route icon

image

image

### CODE REVIEW

**Comment by ChaosEmpire** [comment]
While searching for the Tab ROUTES i detected the route button in AREAS
edit button works as expected, edited 2 routes successful

Missing:
As there is no route tab , like for geofence, you cant delete routes, or create one by just adding them

**Comment by FimoJones** [comment]
Looks good. It is a very nice improvement and from my perspective, works as intended.

**Comment by Expl0dingBanana** [comment]
image

**Comment by Expl0dingBanana** [comment]
@ChaosEmpire RouteCalcs do not have a name and take their name from the area.  For that reason we do not have a routecalc page.  If you wish to manually edit a routecalc you will need to click on the route icon.  If you wish to assign a different routecalc to the area you will need to use the API.

**Comment by ChaosEmpire** [comment]
@expl0dingbanana

without an own website, you cant delete routes

before database migration, you have been able toi change routes, based on file NAMES

for example, i saved a good working route, when i tested things with overlapping areas and geofence exclude
or for cday things

so i have build several routes, which i was able to change, just by changing the name in the area window

this feature got lost during db migration

so i no longer can choose a route to use in areas, 
and i also cant delete oldroutes, 

its wrong to say routes have had no names, as the name was, like the geofence, the filename you used for that route
like exploding.calc
banana,calc
explodingbanana.calc

3routes you have been able to switch between

for cdays i just took a well calculated route, removed some parts, and have had good routes for some cday specific areas
or i optimized a route myself, and have had the original to compare and also test by switching the routes

its no longer possible at the moment

**Comment by sn0opy** [comment]
It's still possible. Just modify them in the DB instead.

**Comment by Expl0dingBanana** [comment]
Creating a new routecalc
create a file called routefile.txt 
  (https://gist.github.com/Expl0dingBanana/4182a941af7f04b46a7991fe39ffd24e)
curl -x POST -d @routefile.txt http://localhost:5000/api/routecalc
  Check the response for X-URI (you will use this in the next step)

Set routecalc to area
curl -x PATCH -d '{"routecalc": <X-URI>}' http://localhost:5000/api/area/<area_id>
OR
login to DB and set routecalc (use the correct table based on the area) to X-URI

**Pull request merged**
