### PR TITLE
Custom Google Apps domain support in GGL

### PR DESCRIPTION
**Pull request by JabLuszko**
Should work, someone double check please :D

### CODE REVIEW

**Comment by cecpk** [comment]
maybe as an array if more diff domains are in use? :)

**Comment by JabLuszko** [comment]
@cecpk there you go, comma sep list

**Comment by cecpk** [comment]
we wait for #267
already steal code from this 🥇

**Comment by cecpk** [comment]
see https://github.com/Map-A-Droid/MAD/commit/7bead975bee2ea11dc16c5712e8edb18eeb9e5f4

**Pull request closed without merging**
