### PR TITLE
Pause / Unpause workers

### PR DESCRIPTION
**Pull request by Expl0dingBanana**
An API RPC function has been implemented that allows pausing and un-pausing of workers.  The UI has been updated to include this functionality on the devices page.

This implementation is in regards to #589

### CODE REVIEW

**Comment by Expl0dingBanana** [comment]
Device that is active (unpaused)
image
Device after clicking pause
image
Disconnect / reconnect expectation
image

**Comment by fosJoddie** [comment]
When you pause a worker, the icon doesn't change until you reload the settings page

**Comment by Expl0dingBanana** [comment]
The page should auto-refresh after clicking accept on the popup.  Was that not working for you?

**Comment by fosJoddie** [comment]
Pause works as it should, and resume also gets the worker going agian. 
Unpausing causes feedback as it should.

Tried to pause it again now:
- after confirming the dialog the "loading" screen flashes briefly and then goes away
but then, some time later, the "successfully paused" message comes up and the icon updates.

**Comment by Expl0dingBanana** [comment]
The loading modal going away is now tied to the API call finishing

**Pull request merged**
