### PR TITLE
open new quest menu for 0.171.0

### PR DESCRIPTION
**Pull request by cecpk**

### CODE REVIEW

**Comment by acocalypso** [comment]
I made some tests with this PR and found the followng:

While in quest mode the bot does this:

open quest page - stuck at today screen - close quest menu - spin stop - go to next stop - repeat

while spinning stop I get the following message in the log:

`[03-27 08:01:57.36] [         Walker10] [       WorkerQuests:818 ] [ WARNING] Failed getting quest but got items - quest box is probably full. Start clean`

After that the bot just continues

I also saw a few of this exceptions:

```
[03-27 07:54:48.43] [clear_thread_Walker12] [              start:63  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):

  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fd704e40ae8>
    └ <Thread(clear_thread_Walker12, started daemon 140558441838336)>

  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function install_thread_excepthook.<locals>.run_thread at 0x7fd6e8cd6730>
    └ <Thread(clear_thread_Walker12, started daemon 140558441838336)>

> File "start.py", line 57, in run_thread
    run_thread_old(*args, **kwargs)
    │               │       └ {}
    │               └ (<Thread(clear_thread_Walker12, started daemon 140558441838336)>,)
    └ <function Thread.run at 0x7fd704e408c8>

  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │             │             └ <Thread(clear_thread_Walker12, started daemon 140558441838336)>
    │             └ <Thread(clear_thread_Walker12, started daemon 140558441838336)>
    └ <Thread(clear_thread_Walker12, started daemon 140558441838336)>

  File "/home/aco/MAD/mapadroid/worker/WorkerQuests.py", line 432, in _clear_thread
    self._clear_quests(self._delay_add)
    │    │             │    └ 0
    │    │             └ <mapadroid.worker.WorkerQuests.WorkerQuests object at 0x7fd6e0665278>
    │    └ <function MITMBase._clear_quests at 0x7fd6e8d99bf8>
    └ <mapadroid.worker.WorkerQuests.WorkerQuests object at 0x7fd6e0665278>

  File "/home/aco/MAD/mapadroid/worker/MITMBase.py", line 202, in _clear_quests
    x, y = self._resocalc.get_quest_listview(self)[0], \
    │      │    │         │                  └ <mapadroid.worker.WorkerQuests.WorkerQuests object at 0x7fd6e0665278>
    │      │    │         └ <function Resocalculator.get_quest_listview at 0x7fd6e8d8fd90>
    │      │    └ <class 'mapadroid.utils.resolution.Resocalculator'>
    │      └ <mapadroid.worker.WorkerQuests.WorkerQuests object at 0x7fd6e0665278>
    └ 672.8971962616822

  File "/home/aco/MAD/mapadroid/utils/resolution.py", line 25, in get_quest_listview
    click_y = int(self._screen_y / 5.82)
                  │    └ '1280'
                  └ <mapadroid.worker.WorkerQuests.WorkerQuests object at 0x7fd6e0665278>

TypeError: unsupported operand type(s) for /: 'str' and 'float'

```

**Comment by temp666** [comment]
it's work with this commit

**Comment by acocalypso** [comment]
yep now its working fine for me.

**Comment by crhbetz** [comment]
Now looking good here, too! 👍

**Comment by cecpk** [comment]
merge with force then - thx for testing

**Comment by krzee** [comment]
works here

**Comment by moltova** [comment]
I just installed this PR and started it manually. The scan found all quests. Works fine for me !

**Comment by acocalypso** [comment]
When will it be merged?

**Comment by temp666** [comment]
i think it's will be merged when 0.171 is forced

**Comment by sn0opy** [comment]
> merge with force then - thx for testing

**Comment by JabLuszko** [comment]
People reports that this branch still works with devices with 169.0, so in theory there is no need to wait for a force.

**Comment by krzee** [comment]
can confirm. I have 1 64bit device questing still on 0.169.3

**Comment by ChaosEmpire** [comment]
Running this branch since days, in a mixed environment of 169.3, 171,0 and 171.2
no issues

**Pull request merged**
