### PR TITLE
Add 1080p support to Google Screens OCR

### PR DESCRIPTION
**Pull request by spammer23**
Credits to Silverthumbz from Discord

### CODE REVIEW

**Comment by LucianoNeo** [comment]
NOt working on my device, cause MAD need to roll down to click allow button

[10-14 11:34:47.38] [          zenfone] [         WorkerBase:636 ] [I] Found ScreenType.UNDEFINED multiple times in a row (2)
[10-14 11:34:47.38] [          zenfone] [         WorkerBase:649 ] [E] Undefined screentype!
[10-14 11:34:47.61] [          zenfone] [         screenPath:493 ] [I] Processing Screen: ScreenType.CONSENT
[10-14 11:34:47.61] [          zenfone] [         screenPath:455 ] [I] _handle_ggl_consent_screen: Click accept button
[10-14 11:34:58.40] [          zenfone] [         WorkerBase:636 ] [I] Found ScreenType.UNDEFINED multiple times in a row (3)
[10-14 11:34:58.41] [          zenfone] [         WorkerBase:649 ] [E] Undefined screentype!
[10-14 11:34:58.64] [          zenfone] [         screenPath:493 ] [I] Processing Screen: ScreenType.CONSENT
[10-14 11:34:58.64] [          zenfone] [         screenPath:455 ] [I] _handle_ggl_consent_screen: Click accept button
[10-14 11:35:02.61] [          zenfone] [            control:160 ] [I] MADmin: Making screenshot
[10-14 11:35:09.43] [          zenfone] [         WorkerBase:636 ] [I] Found ScreenType.UNDEFINED multiple times in a row (4)
[10-14 11:35:09.43] [          zenfone] [         WorkerBase:638 ] [W] Screen is frozen
Screenshot_1
!

**Comment by domizei385** [comment]
This might help you with the scrolling: https://github.com/Map-A-Droid/MAD/pull/1216

**Comment by spammer23** [comment]
thanks @domizei385 added it.
Somebody got the click points for 1080p? (last device died)

**Comment by Boby360** [comment]
830,1638 for 1080

**Comment by Boby360** [comment]
Watched it in action, and confirmed the new coords work.

**Comment by Boby360** [comment]
This can be closed due to:
https://github.com/Map-A-Droid/MAD/pull/1290

**Pull request closed without merging**
