### PR TITLE
updating example config to separate OCR/MITM mode

### PR DESCRIPTION
**Pull request by krzee**
This is not ready to merge!!!
please take a look and double check the config, im not even 100% positive about some things, like autohatch for example...
but this should get the ball rolling 👌

### CODE REVIEW

**Comment by krzee** [comment]
dont just look at the patch, view the whole file please!

**Comment by krzee** [comment]
is that the only problem? i figured there would be more :D

**Comment by sn0opy** [comment]
@krzee could you have another look into this in case this is still a wanted feature?

**Comment by krzee** [comment]
I've been away for a bit, I'm totally unaware of any further config changes. I still think it makes sense, but i wont be home until the end of the month. It's a really easy change to make for anybody who is certain they know what config options are ocr/mitm.

**Comment by krzee** [comment]
The more options that get added the less im able to correctly separate them. If this is a desired enhancement then somebody else should separate them. If not, feel free to just close the ticket

**Comment by sn0opy** [comment]
Closing this for now. Guess we will have another look into it in the upcoming weeks.

**Pull request closed without merging**
