### PR TITLE
madmin quests: add pokestop lat / lon and link it to OSM

### PR DESCRIPTION
**Pull request by sprintnudel**

### CODE REVIEW

**Comment by sn0opy** [comment]
Why OSM if everything else is linking to Google Maps?

**Comment by sprintnudel** [comment]
You guys use OSM everywhere, no? Generally I prefer OSM because it has more detail and usually is mor eup to date compared to Google maps.

**Comment by sn0opy** [comment]
Uhm, no. We don't. Every link on the madmin map points to Google Maps, so I'd say we stick to Gmaps here too for now. Feel free to add an extra option to let instance owners decide which one they want to use.

**Comment by sprintnudel** [comment]
Yeah in that case it makes sense. Will open another PR.

**Pull request closed without merging**
