### PR TITLE
Update the Dockerfile for new defaults

### PR DESCRIPTION
**Pull request by muckelba**
untested, but should work

### CODE REVIEW

**Comment by memcoreDE** [comment]
It's, not working.
Since the update, i have an error.

`start.py: error: argument -pwhn/--pokemon_webhook_nonivs: ignored explicit argument 'true'`

**Comment by sn0opy** [comment]
@memcoreDE you most certainly broke something in your setup then. `pokemon_webhook_nonivs` does still exist and you simply have to write `pokemon_webhook_nonivs` into your config file. It does not have any value.

**Comment by memcoreDE** [comment]
Thanks.
But i have not changed the config. I have only updated the latest Commits/Docker-Image since 24h.
Ther is a issue with the configfile, i have disabled webhooks and have another errors.
`start.py: error: unrecognized arguments: --with_madmin=true --geofence_file_path=configs/geofences`  

Thanks, i will check the whole config.

**Comment by sn0opy** [comment]
Read #announcements in Discord or https://github.com/Map-A-Droid/MAD/pull/1023

**Pull request merged**
