### PR TITLE
Display IV0 on madmin

### PR DESCRIPTION
**Pull request by korentzari**
IV0 is not iv not scan

### CODE REVIEW

**Comment by darkelement1987** [comment]
Can you give a better description what this PR Will change?

**Comment by korentzari** [comment]
MADAMIN not display information when pokemon is IV0 ( atk=0 , def=0 , sta=0 ) 
it is more relevant to test another parameter than attack, defense, stamina which can be zero.

IV0 != NotDetectIV

**Comment by darkelement1987** [comment]
Some people like 0% mons for weird reasons

**Comment by muddpunk** [comment]
I collect 0% Mon. Don't deny me a zero 👀

**Comment by ColdShadow80** [comment]
No need for 0% stats, even colectors sould not be using MADadmin to get notifications of wen they apear, use frontend

**Comment by hartlomiej** [comment]
@darkelement1987 @muddpunk @ColdShadow80 check what it does before commenting
@korentzari good PR

**Pull request merged**
