### PR TITLE
Updated possible dittos list

### PR DESCRIPTION
**Pull request by cyphercris**
Update possible dittos list

### CODE REVIEW

**Comment by JabLuszko** [comment]
Those are event pokemon with different behavior than "normal" Dittos - we do not know if this is temporary or not (especially that Voltorb should go shiny in May, so deleted from that list). I don't think anyone is having any problems in finding Dittos now with increased spawns and million of those. I would wait for confirmation that those still can be Dittos after the event ends.

**Comment by cyphercris** [comment]
So can be delete after event :dagger:

**Comment by ccev** [comment]
They seem to still be be Ditto disguises.

     SELECT * FROM pokemon WHERE pokemon_id = 590 AND weather_boosted_condition > 0 AND (individual_attack < 4 OR individual_defense < 4 OR individual_stamina < 4 OR cp_multiplier < .3) ORDER BY disappear_time desc limit 10;

This query to detect possible Foongus Dittos definitely returns recent results for me. The most recent one from 5 hours ago.

Additionally, Venonat has its shiny released today (1PM local), so it stops being a possible disguise and should be removed from the list.

**Comment by cyphercris** [comment]
Remove Voltrob

**Comment by cyphercris** [comment]
Also Skitty should be remove

**Comment by JabLuszko** [comment]
273 aka Seedot should be gone too :)

**Pull request merged**
