### PR TITLE
Make Webhook send Gender/Weather boost info

### PR DESCRIPTION
**Pull request by PixelBurstHD**
As per the title, created to PA standard - not tested with anything else.
image

Needs testing with RM

### CODE REVIEW

**Comment by PixelBurstHD** [comment]
OK so just to recap on what we discussed Dongo - 

- Weather needs to be passed as well
- boosted_weather needs to show on non-iv scanned mons too as this data is available

I scratched my head over this for a while, but I'll come back with fresh eyes tomorrow and go at it again! 👍

**Comment by peterbaumert** [comment]
this would be great :)

**Comment by JimBim89** [comment]
Adding these to non-iv checked mons seems to work...

`form=wild_mon['pokemon_data']['display']['form_value'],`
`gender=wild_mon['pokemon_data']['display']['gender_value'],`
`boosted_weather=wild_mon['pokemon_data']['display']['weather_boosted_value']`

**Comment by PixelBurstHD** [comment]
> Adding these to non-iv checked mons seems to work...
> 
> `form=wild_mon['pokemon_data']['display']['form_value'],`
> `gender=wild_mon['pokemon_data']['display']['gender_value'],`
> `boosted_weather=wild_mon['pokemon_data']['display']['weather_boosted_value']`

Awesome work! Did you want to rebase it on the latest code do a new PR and I'll shut this one? Lots of conflicts now its a bit old :D

**Comment by fosJoddie** [comment]
just FYI @PixelBurstHD  
you can rebase against a branch and force push it to update this PR, should resolve your conflicts easy enough too =)

**Comment by PixelBurstHD** [comment]
👍 I can also do that later this evening then if you want! Your call JimBim89 would rather you pushed your success after I failed so bad though :P

**Comment by sn0opy** [comment]
@PixelBurstHD please re-check the PR. Right now it conflicts with latest changes.

**Comment by PixelBurstHD** [comment]
closing and reopening as unable to resolve conflicts due to commit order(?)

**Pull request closed without merging**
