### PR TITLE
FIXED: automated logout on timeout

### PR DESCRIPTION
**Pull request by domizei385**

### CODE REVIEW

**Comment by clburlison** [comment]
Works over here. Thanks!

**Comment by moltova** [comment]
Tested and works fine. thx

**Review by Swiss-Rainbow — APPROVED** [review]
Tested and works fine. thx

**Comment by marcb1387** [comment]
Pulled and working for me as well.

**Comment by andi2022** [comment]
Thx for this pr. It is working fine.

**Comment by ChaosEmpire** [comment]
German translation should be 
ABMELDEN

AUSLOGGEN is wrong for that button

**Comment by Expl0dingBanana** [comment]
Can you update the German translation prior to merge?

**Comment by mpw1337** [comment]
Pulled and working like a charm, before 5/13 devices were unable to login, now all are back online again.

**Comment by Expl0dingBanana** [comment]
Thanks for this fix!

**Pull request merged**
