### PR TITLE
Update RM DB with Gyms in Battle & EX Eligible Gyms

### PR DESCRIPTION
**Pull request by zaeshu**
This will update RocketMap database columns is_in_battle and park under table gym.

### CODE REVIEW

**Comment by cecpk** [comment]
do we have this fields in RM DB? 🍡

**Comment by temp666** [comment]
yes, with fresh db.
But for exists db is no migration in OSM-RocketMap.

**Comment by sn0opy** [comment]
May I suggest one change please? I'd rather have a seperate field to be compatible with Monocle. 

Instead of using `park`, we should actually use `is_ex_raid_eligible`, so we can add the same field to the Monocle db as well, since Monocle's fort's `park` collumn works differently.

**Comment by krzee** [comment]
monocle park just needs to be set to 1 and then park_id could be set to anything non null/0

**Comment by sn0opy** [comment]
> to be supported by pmsf monocle park just needs to be set to 1 and then park_id could be set to anything non null/0

it could, but that's not the way Monocle works. The `park` field is a varchar that holds the park's type.

**Comment by krzee** [comment]
i dont think monocle is coming back, only thing keeping the format alive is MAD... as long as its valid to pmsf while looking at the monocle db id think mad is free to do as it likes here :)

**Comment by sn0opy** [comment]
We now have an extra field in RM and Monocle which handles this.

**Pull request closed without merging**
