### PR TITLE
Dynamically reload settings from mappings.json

### PR DESCRIPTION
**Pull request by michikrug**
This PR adds the functionality to dynamically update the settings for all workers on-the-fly when the mappings.json file has changed.

This enables easy editing of the settings and mappings in MADmin without the need for restarting the whole process to use the new ones.

### CODE REVIEW

**Comment by simonbuehler** [comment]
works great, pls merge

**Comment by sn0opy** [comment]
Due to the huge quest/iv update, this PR will break things. Do you mind to have another look into it?

**Comment by michikrug** [comment]
Uhh. Sure, but may take a little while.

**Comment by michikrug** [comment]
@sn0opy should be okay now

**Comment by michikrug** [comment]
Stopping the worker to force it to re-register should solve the problems

**Comment by michikrug** [comment]
Updated to recent changes.

**NOT TESTED!**

**Pull request merged**
