### PR TITLE
hopefully fix egg webhooks for PA support

### PR DESCRIPTION
**Pull request by fosJoddie**
whoopsie

### CODE REVIEW

**Comment by evilmoses** [comment]
Let me try quickly before we merge

**Comment by TiMXL73** [comment]
PA isn't looking at any value (int or string) to determine if it's an egg or raid, it's just looking if the key `pokemon_id` exists in the payload to differentiate eggs from raids. As such, `pokemon_id` should be removed altogether.

Why was it added though is my question (unused in PA's EggEvent)?

```
elif kind == 'raid' and not message.get('pokemon_id'):
            # RM sends None, M sends 0 for eggs
            return EggEvent(message)
        elif kind == 'raid' and message.get('pokemon_id'):
            # RM/M send Monster ID in raids
            return RaidEvent(message)
```

**Comment by fosJoddie** [comment]
@TiMXL73  did you even read the code you pasted?

```
elif kind == 'raid' and not message.get('pokemon_id'):
            # RM sends None, M sends 0 for eggs
```

will trigger if key pokemon_id is not in message
OR 
if key is there and is the number 0
which is how it has always been with messages from monocle btw

**Comment by TiMXL73** [comment]
Apologies. You are correct and I need sleep.

**Pull request merged**
