### PR TITLE
Correct wording on Research task

### PR DESCRIPTION
**Pull request by fosJoddie**
Task text for spining new pokestops updated to reflect what's actually used in game

### CODE REVIEW

**Comment by cecpk** [comment]
merge after translation - do this the next days.
French guys! Help me. Thx

**Comment by Mystic018** [comment]
hey, im french , i can help you ;)

**Comment by fosJoddie** [comment]
I guess this one only needed to update they keywords right? Cause I have no idea if the actual translations is right

**Comment by cecpk** [comment]
No problem. My job 😜

**Comment by sn0opy** [comment]
> No problem. My job 😜

you had one job. At least you said so. Ready to merge?

**Comment by cecpk** [comment]
merge it - translating after that ^^

**Pull request merged**
