### PR TITLE
Implement a quicker but less effective way to calculate routes

### PR DESCRIPTION
**Pull request by fosJoddie**
Make it possible to sacrifice route optimization in favor of much faster route calculcations

new setting: 
`route_calc_algorithm`

default value is `optimized` - alternate value is `quick` to use the alternative calculations

### CODE REVIEW

**Comment by fosJoddie** [comment]
Benchmark:

Calculating a quest route of almost 300 stops:
Quick: 305 ms
image

Optimized: 119253 ms (almost 2 minutes)
image


As you can see, the quick route is visibly "worse"

**Comment by bbdoc** [comment]
Love it... mainly for quests as mine can take up to 48h to recalculate... so in the end I'm working with non optimized routes as well as new stops are not being visited. Will test ;-)

**Comment by fosJoddie** [comment]
Rebased against dev and moved the new setting into device setting

**Comment by krzee** [comment]
this is useful when processing a large route on a raspberry pi <3
thank you

**Comment by fosJoddie** [comment]
rebased against latest dev

**Comment by korentzari** [comment]
Add option on zone configuration and not devices ?

**Comment by cecpk** [comment]
Merged in dev - edit: setting on area not on device

**Pull request closed without merging**
