### PR TITLE
Scroll down in google consent screen

### PR DESCRIPTION
**Pull request by domizei385**
...only used and tested with x96 mini, so may not fit all sizes.

### CODE REVIEW

**Comment by acocalypso** [comment]
This PR fixed my issue with the annoying screen.
It's now running since 3 days and I can verify that the consent screen is handled.

**Comment by ccev** [comment]
Instead of tapping and holding, wouldn't it be possible to press the `Page Down` button?

**Comment by crhbetz** [comment]
End button even :-) Add this or similar to `websocket/communicator.py`:
```
def end_button(self) -> bool:
    return self.__run_and_ok("touch keyevent 123", self.__command_timeout)
```

(I started looking into a OCR based solution for this. However, for some reason tesseract will find every single word of the consent window except the `Accept` 🤷 . Currently looking for `Cancel` and tapping the opposite position as `width minus x-coordinate of cancel` as a test).

**Comment by acocalypso** [comment]
Merge?

**Comment by cyphercris** [comment]
This pr Fix my problem.

**Pull request merged**
